# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    context-path: /management
    #TODO : issue with spring-boot 1.5.1
    #see https://github.com/spring-projects/spring-boot/issues/8255
    security:
        enabled: false
    ###############################################################
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true

spring:
    application:
        name: klask
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: klask@localhost
    swagger:
        title: klask API
        description: klask API documentation
        version: 0.1.0
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
    ribbon:
        # comma seperated list of profiles to show a ribbon on the GUI
        displayOnActiveProfiles: dev

# ===================================================================
# Klask app specific properties
# ===================================================================
klask:
    crawler:
        workingDirectory: /tmp/klask/klask-working-directory/
        privateKey: "vMky9q9ozQBcKU8h-iHi"
        userGit: "jeremie"
        directoriesToScan: /repo
        batchSize: 25
        directoriesToExclude:
            - .svn
            - .git
            - node_modules
        extensionsToExclude:
            - sha1
            - md5
        filesToExclude: .project,.classpath,swagger-ui.js,angular.min.js.map,bootstrap.css.map,bootstrap.css.map,angular.min.js.map,jquery.min.map,angular.min.js
        extensionsToRead: java,properties,txt,xml,js,jsp,html,htm,php,asm,md,json,sh,bat,sql,yml,yaml,pom,scala,dtd,c,cpp,h,pc,as,mxml,xsl,xslt,tld,asp,jrxml,conf,desc,gs,less,scss,css,ini,groovy,gradle,policy,py,go,toml,rs

