apiVersion: v2
name: klask
description: A Helm chart for Klask - Modern code search engine
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/klask-io/klask-io
sources:
  - https://github.com/klask-io/klask-io
maintainers:
  - name: Klask Team
keywords:
  - search
  - code
  - rust
  - react
dependencies:
  - name: postgresql
    version: "~15.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
