# Helm Chart Publishing Workflow
# This workflow publishes the Helm chart to OCI registry
# Docker images are handled by the main ci.yml workflow

name: Publish Helm Chart

on:
  push:
    branches: [ main, master, rust-modernization ]
    tags: [ 'v*' ]
  workflow_run:
    workflows: ["CI/CD"]
    branches: [ main, master, rust-modernization ]
    types:
      - completed

env:
  REGISTRY: ghcr.io

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    # Only run if CI workflow succeeded or on direct push
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Helm Chart Publishing
    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.14.0'

    - name: Update Helm dependencies
      run: |
        cd charts/klask
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update
        helm dependency update

    - name: Package Helm chart
      run: |
        cd charts
        helm package klask

    - name: Push Helm chart to OCI registry
      run: |
        cd charts
        # Get the chart version
        CHART_VERSION=$(helm show chart klask | grep '^version:' | awk '{print $2}')
        
        # Login to GHCR for Helm
        echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin
        
        # Push the chart
        helm push klask-${CHART_VERSION}.tgz oci://${{ env.REGISTRY }}/${{ github.repository_owner }}

  update-chart-values:
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/rust-modernization' || github.head_ref == 'rust-modernization'
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Chart.yaml with new images
      run: |
        cd charts/klask
        
        # Get the image digest from the previous job
        BACKEND_IMAGE="${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_BACKEND }}:latest"
        FRONTEND_IMAGE="${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_FRONTEND }}:latest"
        
        # Update values.yaml with the new image references
        sed -i "s|repository: klask-backend|repository: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_BACKEND }}|g" values.yaml
        sed -i "s|repository: klask-frontend|repository: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_FRONTEND }}|g" values.yaml
        sed -i "s|tag: latest|tag: latest|g" values.yaml

    - name: Commit updated chart
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add charts/klask/values.yaml
        git diff --staged --quiet || git commit -m "chore: update chart with new image references [skip ci]"
        git push
